kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  server:
    base-url: http://localhost:8090
    http:
      port: 8090

  metrics:
          web-instrumentation:
            - name: metricsEndpoint
              url-pattern: /metrics/*
            - name: customersEndpoint
              url-pattern: /v1/users/*

