kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  server:
    base-url: http://localhost:8090
    http:
      port: 8090

  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      disk-space-health-check:
        threshold: 1000000000
  logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                     <Configuration name="users">
                         <Appenders>
                             <Console name="console" target="SYSTEM_OUT">
                                 <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                             </Console>
                             <Socket name="logstash" host="45b3a890-bc4a-4fa6-b1b0-74ff1f25736c-ls.logit.io" port="14448" protocol="tcp">
                                 <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                             </Socket>
                         </Appenders>
                         <Loggers>
                             <!-- Default logger -->
                             <Root level="all">
                                 <AppenderRef ref="console" level="info"/>
                                 <AppenderRef ref="logstash" level="trace"/>
                             </Root>
                         </Loggers>
                     </Configuration>'

  metrics:
          web-instrumentation:
            - name: metricsEndpoint
              url-pattern: /metrics/*
            - name: customersEndpoint
              url-pattern: /v1/users/*

