apiVersion: v1
kind: Service
metadata:
  name: postgres-posts
spec:
  type: ClusterIP
  ports:
  - port: 5441 #na tega se connectajo servici
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-posts