apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: cleptes/users:0.01
        name: users
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379

        ports:
        - containerPort: 8090
          name: server
          protocol: TCP
        #resources:
         #limits:
          #cpu: 500m
        #livenessProbe:
         # httpGet:
          #  path: /health
           # port: 8080
          #initialDelaySeconds: 5
          #periodSeconds: 3