apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: cleptes/users:0.02
        name: users
        imagePullPolicy: Always
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.16.117:30977
          - name: KUMULUZEE_VERSION
            value: 1.0.1
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-users:5440/users
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: userdb
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres

        ports:
        - containerPort: 8090
          name: server
          protocol: TCP
        #resources:
         #limits:
          #cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 3